### ISSUE TITLE
How to sort?

### ISSUE THREAD

**Issue by taksyon** [Strobel273/InventiveInventoryIssues#1]
**Mod Version & Minecraft Version**
0.4.0 - 1.20.4
**Describe the bug**
Maybe I'm misunderstanding, but I don't see a clear description of how to use the sorting feature on the modrinth page.

**To Reproduce**

**Expected behavior**
I expect to see a clear guide on how to use the mod's features

**Screenshots**

**Additional context**

**Comment by taksyon** [comment]
Thank you for the clarification. Probably just adding a section for the default keybindings on the modrinth page would suffice. 

I also would suggest publishing the source code here on github to help establish trust with users, but that's my opinion, and may not be aligned with your teams goals. I personally prefer to have the ability to view the source code for mods I install, so for now I will use a different sorting mod. But I wish your team the best and hope that Inventive Inventory is wildly successful, seeing millions of downloads. Cheers!

**Comment by Strobel273** [comment]
Thanks for the feedback. Adding a section is a great idea, we will make that happen.
Also we will strongly consider to publish the source code.
Thank you
